# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myApps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MarqueeLabel/Swift'
  pod 'lottie-ios'
  pod 'RealmSwift'

  # Pods for myApps

  target 'myAppsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myAppsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
