# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TableViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableViewDemo
  pod 'Kingfisher', '~> 4.0'
  pod 'RealmSwift'
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'UIScrollView-InfiniteScroll', '~> 1.0.0'
  
  target 'TableViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
