source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Movreak' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movreak
  pod 'Moya'
  pod 'RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  
  pod 'UITextView+Placeholder', '~> 1.2'
  pod 'DCPathButton', '~> 2.1.3'
  pod 'GSKStretchyHeaderView'
  pod 'CMTabbarView', :git => "https://github.com/moyunmo/CMTabbarView.git", :branch => "master"
  pod 'DKImagePickerController'
  pod 'youtube-ios-player-helper', '~> 0.1.4'
  pod 'FlexiblePageControl', :git => "https://github.com/shima11/FlexiblePageControl.git"
  pod 'LGSemiModalNavController'
  pod 'CSNotificationView', '~> 0.5'
  pod 'DZNEmptyDataSet'
  pod 'UIScrollView-InfiniteScroll', '~> 1.0.0'
  pod 'RDGliderViewController-Swift'
  pod 'UIImageColors'
  
  pod 'SDWebImage', '~> 3.8'
  pod 'DateToolsSwift'
  pod 'Dollar'
  pod 'Cent'
  pod 'Kanna'

  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  pod 'TwitterKit'
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  
  pod 'AZSClient'
  
  target 'MovreakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovreakUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
