# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rxmoya Testing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rxmoya Testing

  pod 'Moya/RxSwift', '~> 12.0'

  target 'Rxmoya TestingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rxmoya TestingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
